# Generated by Django 3.2.8 on 2021-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Details', models.CharField(max_length=50)),
                ('Mail_Details', models.CharField(max_length=20)),
                ('Mobile_Details', models.CharField(max_length=10, null=True)),
                ('Age_Details', models.IntegerField(null=True)),
                ('upload', models.FileField(upload_to='')),
                ('Job_Details', models.CharField(max_length=30)),
            ],
        ),
    ]
