# Generated by Django 3.2.8 on 2021-10-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='upload',
        ),
    ]
